#Cau hinh
server.id=1
server.log.display=false
server.port=14444

db.host=localhost
db.port=3306
db.user=nso
db.password=123456
db.dbname=db_shop
db.driver=com.mysql.cj.jdbc.Driver
db.minconnections=15
db.maxconnections=20

mongodb.host=localhost
mongodb.port=27017
mongodb.dbname=admin
mongodb.user=root
mongodb.password=

websocket.host=ws://localhost
websocket.port=8020

game.upgrade.percent.add=0
game.store.discount=0

game.shinwa.active=true
game.shinwa.fee=5000
game.shinwa.max=10000
game.shinwa.player.max=20

game.arena.active=true
game.login.limit=20
game.quantity.display.max=65535

server.notification=Welcome to NSO Server

game.data.version=56
game.item.version=46
game.map.version=36
game.skill.version=35

threadPoolSize=50
scheduledPoolSize=20

game.EXP=1
game.event=com.nsoz.event.LunarNewYear
client.data.size.max=1024